version: 0.2

phases:
  install:
    commands:

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  
  build:
    commands:

      # Use AWS SAM to package the application by using AWS CloudFormation
      - echo "hello this is pr/ not so amazing branch" 

artifacts:
  type: zip
  files:
    - template-export.yml
